export default [
  {
    kode_kabupaten: '1102',
    nama_kabupaten: 'ACEH TENGGARA',
    is_kota: 0,
    kode_provinsi: '11',
  },
  {
    kode_kabupaten: '1105',
    nama_kabupaten: 'ACEH BARAT',
    is_kota: 0,
    kode_provinsi: '11',
  },
  {
    kode_kabupaten: '1103',
    nama_kabupaten: 'ACEH TIMUR',
    is_kota: 0,
    kode_provinsi: '11',
  },
  {
    kode_kabupaten: '1101',
    nama_kabupaten: 'ACEH SELATAN',
    is_kota: 0,
    kode_provinsi: '11',
  },
  {
    kode_kabupaten: '1104',
    nama_kabupaten: 'ACEH TENGAH',
    is_kota: 0,
    kode_provinsi: '11',
  },
  {
    kode_kabupaten: '1106',
    nama_kabupaten: 'ACEH BESAR',
    is_kota: 0,
    kode_provinsi: '11',
  },
  {
    kode_kabupaten: '1111',
    nama_kabupaten: 'BIREUEN',
    is_kota: 0,
    kode_provinsi: '11',
  },
  {
    kode_kabupaten: '1116',
    nama_kabupaten: 'ACEH TAMIANG',
    is_kota: 0,
    kode_provinsi: '11',
  },
  {
    kode_kabupaten: '1173',
    nama_kabupaten: 'KOTA LHOKSEUMAWE',
    is_kota: 1,
    kode_provinsi: '11',
  },
  {
    kode_kabupaten: '1203',
    nama_kabupaten: 'TAPANULI SELATAN',
    is_kota: 0,
    kode_provinsi: '12',
  },
  {
    kode_kabupaten: '1208',
    nama_kabupaten: 'SIMALUNGUN',
    is_kota: 0,
    kode_provinsi: '12',
  },
  {
    kode_kabupaten: '1213',
    nama_kabupaten: 'MANDAILING NATAL',
    is_kota: 0,
    kode_provinsi: '12',
  },
  {
    kode_kabupaten: '1218',
    nama_kabupaten: 'SERDANG BEDAGAI',
    is_kota: 0,
    kode_provinsi: '12',
  },
  {
    kode_kabupaten: '1223',
    nama_kabupaten: 'LABUHANBATU UTARA',
    is_kota: 0,
    kode_provinsi: '12',
  },
  {
    kode_kabupaten: '1273',
    nama_kabupaten: 'KOTA SIBOLGA',
    is_kota: 1,
    kode_provinsi: '12',
  },
  {
    kode_kabupaten: '1278',
    nama_kabupaten: 'KOTA GUNUNGSITOLI',
    is_kota: 1,
    kode_provinsi: '12',
  },
  {
    kode_kabupaten: '1305',
    nama_kabupaten: 'PADANG PARIAMAN',
    is_kota: 0,
    kode_provinsi: '13',
  },
  {
    kode_kabupaten: '1310',
    nama_kabupaten: 'DHARMASRAYA',
    is_kota: 0,
    kode_provinsi: '13',
  },
  {
    kode_kabupaten: '1373',
    nama_kabupaten: 'KOTA SAWAHLUNTO',
    is_kota: 1,
    kode_provinsi: '13',
  },
  {
    kode_kabupaten: '1401',
    nama_kabupaten: 'KAMPAR',
    is_kota: 0,
    kode_provinsi: '14',
  },
  {
    kode_kabupaten: '1406',
    nama_kabupaten: 'ROKAN HULU',
    is_kota: 0,
    kode_provinsi: '14',
  },
  {
    kode_kabupaten: '1471',
    nama_kabupaten: 'KOTA PEKANBARU',
    is_kota: 1,
    kode_provinsi: '14',
  },
  {
    kode_kabupaten: '1504',
    nama_kabupaten: 'BATANGHARI',
    is_kota: 0,
    kode_provinsi: '15',
  },
  {
    kode_kabupaten: '1509',
    nama_kabupaten: 'TEBO',
    is_kota: 0,
    kode_provinsi: '15',
  },
  {
    kode_kabupaten: '1603',
    nama_kabupaten: 'MUARA ENIM',
    is_kota: 0,
    kode_provinsi: '16',
  },
  {
    kode_kabupaten: '1608',
    nama_kabupaten: 'OGAN KOMERING ULU TIMUR',
    is_kota: 0,
    kode_provinsi: '16',
  },
  {
    kode_kabupaten: '1613',
    nama_kabupaten: 'MUSI RAWAS UTARA',
    is_kota: 0,
    kode_provinsi: '16',
  },
  {
    kode_kabupaten: '1701',
    nama_kabupaten: 'BENGKULU SELATAN',
    is_kota: 0,
    kode_provinsi: '17',
  },
  {
    kode_kabupaten: '1706',
    nama_kabupaten: 'MUKO MUKO',
    is_kota: 0,
    kode_provinsi: '17',
  },
  {
    kode_kabupaten: '1801',
    nama_kabupaten: 'LAMPUNG SELATAN',
    is_kota: 0,
    kode_provinsi: '18',
  },
  {
    kode_kabupaten: '1806',
    nama_kabupaten: 'TANGGAMUS',
    is_kota: 0,
    kode_provinsi: '18',
  },
  {
    kode_kabupaten: '1811',
    nama_kabupaten: 'MESUJI',
    is_kota: 0,
    kode_provinsi: '18',
  },
  {
    kode_kabupaten: '1901',
    nama_kabupaten: 'BANGKA',
    is_kota: 0,
    kode_provinsi: '19',
  },
  {
    kode_kabupaten: '1906',
    nama_kabupaten: 'BELITUNG TIMUR',
    is_kota: 0,
    kode_provinsi: '19',
  },
  {
    kode_kabupaten: '2104',
    nama_kabupaten: 'LINGGA',
    is_kota: 0,
    kode_provinsi: '21',
  },
  {
    kode_kabupaten: '1108',
    nama_kabupaten: 'ACEH UTARA',
    is_kota: 0,
    kode_provinsi: '11',
  },
  {
    kode_kabupaten: '1110',
    nama_kabupaten: 'ACEH SINGKIL',
    is_kota: 0,
    kode_provinsi: '11',
  },
  {
    kode_kabupaten: '1109',
    nama_kabupaten: 'SIMEULUE',
    is_kota: 0,
    kode_provinsi: '11',
  },
  {
    kode_kabupaten: '1107',
    nama_kabupaten: 'PIDIE',
    is_kota: 0,
    kode_provinsi: '11',
  },
  {
    kode_kabupaten: '1115',
    nama_kabupaten: 'NAGAN RAYA',
    is_kota: 0,
    kode_provinsi: '11',
  },
  {
    kode_kabupaten: '1112',
    nama_kabupaten: 'ACEH BARAT DAYA',
    is_kota: 0,
    kode_provinsi: '11',
  },
  {
    kode_kabupaten: '1114',
    nama_kabupaten: 'ACEH JAYA',
    is_kota: 0,
    kode_provinsi: '11',
  },
  {
    kode_kabupaten: '1172',
    nama_kabupaten: 'KOTA SABANG',
    is_kota: 1,
    kode_provinsi: '11',
  },
  {
    kode_kabupaten: '1113',
    nama_kabupaten: 'GAYO LUES',
    is_kota: 0,
    kode_provinsi: '11',
  },
  {
    kode_kabupaten: '1117',
    nama_kabupaten: 'BENER MERIAH',
    is_kota: 0,
    kode_provinsi: '11',
  },
  {
    kode_kabupaten: '1202',
    nama_kabupaten: 'TAPANULI UTARA',
    is_kota: 0,
    kode_provinsi: '12',
  },
  {
    kode_kabupaten: '1171',
    nama_kabupaten: 'KOTA BANDA ACEH',
    is_kota: 1,
    kode_provinsi: '11',
  },
  {
    kode_kabupaten: '1174',
    nama_kabupaten: 'KOTA LANGSA',
    is_kota: 1,
    kode_provinsi: '11',
  },
  {
    kode_kabupaten: '1207',
    nama_kabupaten: 'DELI SERDANG',
    is_kota: 0,
    kode_provinsi: '12',
  },
  {
    kode_kabupaten: '1118',
    nama_kabupaten: 'PIDIE JAYA',
    is_kota: 0,
    kode_provinsi: '11',
  },
  {
    kode_kabupaten: '1204',
    nama_kabupaten: 'NIAS',
    is_kota: 0,
    kode_provinsi: '12',
  },
  {
    kode_kabupaten: '1212',
    nama_kabupaten: 'TOBA SAMOSIR',
    is_kota: 0,
    kode_provinsi: '12',
  },
  {
    kode_kabupaten: '1209',
    nama_kabupaten: 'ASAHAN',
    is_kota: 0,
    kode_provinsi: '12',
  },
  {
    kode_kabupaten: '1217',
    nama_kabupaten: 'SAMOSIR',
    is_kota: 0,
    kode_provinsi: '12',
  },
  {
    kode_kabupaten: '1201',
    nama_kabupaten: 'TAPANULI TENGAH',
    is_kota: 0,
    kode_provinsi: '12',
  },
  {
    kode_kabupaten: '1214',
    nama_kabupaten: 'NIAS SELATAN',
    is_kota: 0,
    kode_provinsi: '12',
  },
  {
    kode_kabupaten: '1175',
    nama_kabupaten: 'KOTA SUBULUSSALAM',
    is_kota: 1,
    kode_provinsi: '11',
  },
  {
    kode_kabupaten: '1219',
    nama_kabupaten: 'BATU BARA',
    is_kota: 0,
    kode_provinsi: '12',
  },
  {
    kode_kabupaten: '1205',
    nama_kabupaten: 'LANGKAT',
    is_kota: 0,
    kode_provinsi: '12',
  },
  {
    kode_kabupaten: '1224',
    nama_kabupaten: 'NIAS UTARA',
    is_kota: 0,
    kode_provinsi: '12',
  },
  {
    kode_kabupaten: '1210',
    nama_kabupaten: 'LABUHANBATU',
    is_kota: 0,
    kode_provinsi: '12',
  },
  {
    kode_kabupaten: '1274',
    nama_kabupaten: 'KOTA TANJUNG BALAI',
    is_kota: 1,
    kode_provinsi: '12',
  },
  {
    kode_kabupaten: '1215',
    nama_kabupaten: 'PAKPAK BHARAT',
    is_kota: 0,
    kode_provinsi: '12',
  },
  {
    kode_kabupaten: '1220',
    nama_kabupaten: 'PADANG LAWAS UTARA',
    is_kota: 0,
    kode_provinsi: '12',
  },
  {
    kode_kabupaten: '1301',
    nama_kabupaten: 'PESISIR SELATAN',
    is_kota: 0,
    kode_provinsi: '13',
  },
  {
    kode_kabupaten: '1225',
    nama_kabupaten: 'NIAS BARAT',
    is_kota: 0,
    kode_provinsi: '12',
  },
  {
    kode_kabupaten: '1306',
    nama_kabupaten: 'AGAM',
    is_kota: 0,
    kode_provinsi: '13',
  },
  {
    kode_kabupaten: '1275',
    nama_kabupaten: 'KOTA BINJAI',
    is_kota: 1,
    kode_provinsi: '12',
  },
  {
    kode_kabupaten: '1311',
    nama_kabupaten: 'SOLOK SELATAN',
    is_kota: 0,
    kode_provinsi: '13',
  },
  {
    kode_kabupaten: '1302',
    nama_kabupaten: 'SOLOK',
    is_kota: 0,
    kode_provinsi: '13',
  },
  {
    kode_kabupaten: '1374',
    nama_kabupaten: 'KOTA PADANG PANJANG',
    is_kota: 1,
    kode_provinsi: '13',
  },
  {
    kode_kabupaten: '1307',
    nama_kabupaten: 'LIMA PULUH KOTA',
    is_kota: 0,
    kode_provinsi: '13',
  },
  {
    kode_kabupaten: '1402',
    nama_kabupaten: 'INDRAGIRI HULU',
    is_kota: 0,
    kode_provinsi: '14',
  },
  {
    kode_kabupaten: '1312',
    nama_kabupaten: 'PASAMAN BARAT',
    is_kota: 0,
    kode_provinsi: '13',
  },
  {
    kode_kabupaten: '1407',
    nama_kabupaten: 'ROKAN HILIR',
    is_kota: 0,
    kode_provinsi: '14',
  },
  {
    kode_kabupaten: '1375',
    nama_kabupaten: 'KOTA BUKITTINGGI',
    is_kota: 1,
    kode_provinsi: '13',
  },
  {
    kode_kabupaten: '1472',
    nama_kabupaten: 'KOTA DUMAI',
    is_kota: 1,
    kode_provinsi: '14',
  },
  {
    kode_kabupaten: '1403',
    nama_kabupaten: 'BENGKALIS',
    is_kota: 0,
    kode_provinsi: '14',
  },
  {
    kode_kabupaten: '1505',
    nama_kabupaten: 'MUARO JAMBI',
    is_kota: 0,
    kode_provinsi: '15',
  },
  {
    kode_kabupaten: '1408',
    nama_kabupaten: 'SIAK',
    is_kota: 0,
    kode_provinsi: '14',
  },
  {
    kode_kabupaten: '1571',
    nama_kabupaten: 'KOTA JAMBI',
    is_kota: 1,
    kode_provinsi: '15',
  },
  {
    kode_kabupaten: '1501',
    nama_kabupaten: 'KERINCI',
    is_kota: 0,
    kode_provinsi: '15',
  },
  {
    kode_kabupaten: '1604',
    nama_kabupaten: 'LAHAT',
    is_kota: 0,
    kode_provinsi: '16',
  },
  {
    kode_kabupaten: '1506',
    nama_kabupaten: 'TANJUNG JABUNG BARAT',
    is_kota: 0,
    kode_provinsi: '15',
  },
  {
    kode_kabupaten: '1609',
    nama_kabupaten: 'OGAN KOMERING ULU SELATAN',
    is_kota: 0,
    kode_provinsi: '16',
  },
  {
    kode_kabupaten: '1572',
    nama_kabupaten: 'KOTA SUNGAI PENUH',
    is_kota: 1,
    kode_provinsi: '15',
  },
  {
    kode_kabupaten: '1671',
    nama_kabupaten: 'KOTA PALEMBANG',
    is_kota: 1,
    kode_provinsi: '16',
  },
  {
    kode_kabupaten: '1605',
    nama_kabupaten: 'MUSI RAWAS',
    is_kota: 0,
    kode_provinsi: '16',
  },
  {
    kode_kabupaten: '1702',
    nama_kabupaten: 'REJANG LEBONG',
    is_kota: 0,
    kode_provinsi: '17',
  },
  {
    kode_kabupaten: '1610',
    nama_kabupaten: 'OGAN ILIR',
    is_kota: 0,
    kode_provinsi: '16',
  },
  {
    kode_kabupaten: '1707',
    nama_kabupaten: 'LEBONG',
    is_kota: 0,
    kode_provinsi: '17',
  },
  {
    kode_kabupaten: '1672',
    nama_kabupaten: 'KOTA PAGAR ALAM',
    is_kota: 1,
    kode_provinsi: '16',
  },
  {
    kode_kabupaten: '1802',
    nama_kabupaten: 'LAMPUNG TENGAH',
    is_kota: 0,
    kode_provinsi: '18',
  },
  {
    kode_kabupaten: '1703',
    nama_kabupaten: 'BENGKULU UTARA',
    is_kota: 0,
    kode_provinsi: '17',
  },
  {
    kode_kabupaten: '1807',
    nama_kabupaten: 'LAMPUNG TIMUR',
    is_kota: 0,
    kode_provinsi: '18',
  },
  {
    kode_kabupaten: '1708',
    nama_kabupaten: 'KEPAHIANG',
    is_kota: 0,
    kode_provinsi: '17',
  },
  {
    kode_kabupaten: '1812',
    nama_kabupaten: 'TULANG BAWANG BARAT',
    is_kota: 0,
    kode_provinsi: '18',
  },
  {
    kode_kabupaten: '1803',
    nama_kabupaten: 'LAMPUNG UTARA',
    is_kota: 0,
    kode_provinsi: '18',
  },
  {
    kode_kabupaten: '1902',
    nama_kabupaten: 'BELITUNG',
    is_kota: 0,
    kode_provinsi: '19',
  },
  {
    kode_kabupaten: '1808',
    nama_kabupaten: 'WAY KANAN',
    is_kota: 0,
    kode_provinsi: '18',
  },
  {
    kode_kabupaten: '1971',
    nama_kabupaten: 'KOTA PANGKAL PINANG',
    is_kota: 1,
    kode_provinsi: '19',
  },
  {
    kode_kabupaten: '1813',
    nama_kabupaten: 'PESISIR BARAT',
    is_kota: 0,
    kode_provinsi: '18',
  },
  {
    kode_kabupaten: '2105',
    nama_kabupaten: 'KEPULAUAN ANAMBAS',
    is_kota: 0,
    kode_provinsi: '21',
  },
  {
    kode_kabupaten: '1903',
    nama_kabupaten: 'BANGKA SELATAN',
    is_kota: 0,
    kode_provinsi: '19',
  },
  {
    kode_kabupaten: '3172',
    nama_kabupaten: 'KOTA ADM JAKARTA UTARA',
    is_kota: 1,
    kode_provinsi: '31',
  },
  {
    kode_kabupaten: '2101',
    nama_kabupaten: 'BINTAN',
    is_kota: 0,
    kode_provinsi: '21',
  },
  {
    kode_kabupaten: '3202',
    nama_kabupaten: 'SUKABUMI',
    is_kota: 0,
    kode_provinsi: '32',
  },
  {
    kode_kabupaten: '2171',
    nama_kabupaten: 'KOTA BATAM',
    is_kota: 1,
    kode_provinsi: '21',
  },
  {
    kode_kabupaten: '3207',
    nama_kabupaten: 'CIAMIS',
    is_kota: 0,
    kode_provinsi: '32',
  },
  {
    kode_kabupaten: '3173',
    nama_kabupaten: 'KOTA ADM JAKARTA BARAT',
    is_kota: 1,
    kode_provinsi: '31',
  },
  {
    kode_kabupaten: '3212',
    nama_kabupaten: 'INDRAMAYU',
    is_kota: 0,
    kode_provinsi: '32',
  },
  {
    kode_kabupaten: '3203',
    nama_kabupaten: 'CIANJUR',
    is_kota: 0,
    kode_provinsi: '32',
  },
  {
    kode_kabupaten: '3217',
    nama_kabupaten: 'BANDUNG BARAT',
    is_kota: 0,
    kode_provinsi: '32',
  },
  {
    kode_kabupaten: '3208',
    nama_kabupaten: 'KUNINGAN',
    is_kota: 0,
    kode_provinsi: '32',
  },
  {
    kode_kabupaten: '3274',
    nama_kabupaten: 'KOTA CIREBON',
    is_kota: 1,
    kode_provinsi: '32',
  },
  {
    kode_kabupaten: '3213',
    nama_kabupaten: 'SUBANG',
    is_kota: 0,
    kode_provinsi: '32',
  },
  {
    kode_kabupaten: '3279',
    nama_kabupaten: 'KOTA BANJAR',
    is_kota: 1,
    kode_provinsi: '32',
  },
  {
    kode_kabupaten: '3218',
    nama_kabupaten: 'PANGANDARAN',
    is_kota: 0,
    kode_provinsi: '32',
  },
  {
    kode_kabupaten: '3305',
    nama_kabupaten: 'KEBUMEN',
    is_kota: 0,
    kode_provinsi: '33',
  },
  {
    kode_kabupaten: '3310',
    nama_kabupaten: 'KLATEN',
    is_kota: 0,
    kode_provinsi: '33',
  },
  {
    kode_kabupaten: '3315',
    nama_kabupaten: 'GROBOGAN',
    is_kota: 0,
    kode_provinsi: '33',
  },
  {
    kode_kabupaten: '3320',
    nama_kabupaten: 'JEPARA',
    is_kota: 0,
    kode_provinsi: '33',
  },
  {
    kode_kabupaten: '3325',
    nama_kabupaten: 'BATANG',
    is_kota: 0,
    kode_provinsi: '33',
  },
  {
    kode_kabupaten: '3371',
    nama_kabupaten: 'KOTA MAGELANG',
    is_kota: 1,
    kode_provinsi: '33',
  },
  {
    kode_kabupaten: '1222',
    nama_kabupaten: 'LABUHANBATU SELATAN',
    is_kota: 0,
    kode_provinsi: '12',
  },
  {
    kode_kabupaten: '1272',
    nama_kabupaten: 'KOTA PEMATANGSIANTAR',
    is_kota: 1,
    kode_provinsi: '12',
  },
  {
    kode_kabupaten: '1277',
    nama_kabupaten: 'KOTA PADANGSIDIMPUAN',
    is_kota: 1,
    kode_provinsi: '12',
  },
  {
    kode_kabupaten: '1304',
    nama_kabupaten: 'TANAH DATAR',
    is_kota: 0,
    kode_provinsi: '13',
  },
  {
    kode_kabupaten: '1309',
    nama_kabupaten: 'KEPULAUAN MENTAWAI',
    is_kota: 0,
    kode_provinsi: '13',
  },
  {
    kode_kabupaten: '1372',
    nama_kabupaten: 'KOTA SOLOK',
    is_kota: 1,
    kode_provinsi: '13',
  },
  {
    kode_kabupaten: '1377',
    nama_kabupaten: 'KOTA PARIAMAN',
    is_kota: 1,
    kode_provinsi: '13',
  },
  {
    kode_kabupaten: '1405',
    nama_kabupaten: 'PELALAWAN',
    is_kota: 0,
    kode_provinsi: '14',
  },
  {
    kode_kabupaten: '1410',
    nama_kabupaten: 'KEPULAUAN MERANTI',
    is_kota: 0,
    kode_provinsi: '14',
  },
  {
    kode_kabupaten: '3275',
    nama_kabupaten: 'KOTA BEKASI',
    is_kota: 1,
    kode_provinsi: '32',
  },
  {
    kode_kabupaten: '1503',
    nama_kabupaten: 'SAROLANGUN',
    is_kota: 0,
    kode_provinsi: '15',
  },
  {
    kode_kabupaten: '3301',
    nama_kabupaten: 'CILACAP',
    is_kota: 0,
    kode_provinsi: '33',
  },
  {
    kode_kabupaten: '1508',
    nama_kabupaten: 'BUNGO',
    is_kota: 0,
    kode_provinsi: '15',
  },
  {
    kode_kabupaten: '3306',
    nama_kabupaten: 'PURWOREJO',
    is_kota: 0,
    kode_provinsi: '33',
  },
  {
    kode_kabupaten: '3376',
    nama_kabupaten: 'KOTA TEGAL',
    is_kota: 1,
    kode_provinsi: '33',
  },
  {
    kode_kabupaten: '3311',
    nama_kabupaten: 'SUKOHARJO',
    is_kota: 0,
    kode_provinsi: '33',
  },
  {
    kode_kabupaten: '1602',
    nama_kabupaten: 'OGAN KOMERING ILIR',
    is_kota: 0,
    kode_provinsi: '16',
  },
  {
    kode_kabupaten: '3316',
    nama_kabupaten: 'BLORA',
    is_kota: 0,
    kode_provinsi: '33',
  },
  {
    kode_kabupaten: '3471',
    nama_kabupaten: 'KOTA YOGYAKARTA',
    is_kota: 1,
    kode_provinsi: '34',
  },
  {
    kode_kabupaten: '3321',
    nama_kabupaten: 'DEMAK',
    is_kota: 0,
    kode_provinsi: '33',
  },
  {
    kode_kabupaten: '1607',
    nama_kabupaten: 'BANYUASIN',
    is_kota: 0,
    kode_provinsi: '16',
  },
  {
    kode_kabupaten: '3326',
    nama_kabupaten: 'PEKALONGAN',
    is_kota: 0,
    kode_provinsi: '33',
  },
  {
    kode_kabupaten: '3505',
    nama_kabupaten: 'BLITAR',
    is_kota: 0,
    kode_provinsi: '35',
  },
  {
    kode_kabupaten: '3372',
    nama_kabupaten: 'KOTA SURAKARTA',
    is_kota: 1,
    kode_provinsi: '33',
  },
  {
    kode_kabupaten: '1612',
    nama_kabupaten: 'PENUKAL ABAB LEMATANG ILIR',
    is_kota: 0,
    kode_provinsi: '16',
  },
  {
    kode_kabupaten: '3401',
    nama_kabupaten: 'KULON PROGO',
    is_kota: 0,
    kode_provinsi: '34',
  },
  {
    kode_kabupaten: '3510',
    nama_kabupaten: 'BANYUWANGI',
    is_kota: 0,
    kode_provinsi: '35',
  },
  {
    kode_kabupaten: '3501',
    nama_kabupaten: 'PACITAN',
    is_kota: 0,
    kode_provinsi: '35',
  },
  {
    kode_kabupaten: '1674',
    nama_kabupaten: 'KOTA PRABUMULIH',
    is_kota: 1,
    kode_provinsi: '16',
  },
  {
    kode_kabupaten: '3506',
    nama_kabupaten: 'KEDIRI',
    is_kota: 0,
    kode_provinsi: '35',
  },
  {
    kode_kabupaten: '3515',
    nama_kabupaten: 'SIDOARJO',
    is_kota: 0,
    kode_provinsi: '35',
  },
  {
    kode_kabupaten: '3511',
    nama_kabupaten: 'BONDOWOSO',
    is_kota: 0,
    kode_provinsi: '35',
  },
  {
    kode_kabupaten: '1705',
    nama_kabupaten: 'SELUMA',
    is_kota: 0,
    kode_provinsi: '17',
  },
  {
    kode_kabupaten: '3516',
    nama_kabupaten: 'MOJOKERTO',
    is_kota: 0,
    kode_provinsi: '35',
  },
  {
    kode_kabupaten: '3520',
    nama_kabupaten: 'MAGETAN',
    is_kota: 0,
    kode_provinsi: '35',
  },
  {
    kode_kabupaten: '3521',
    nama_kabupaten: 'NGAWI',
    is_kota: 0,
    kode_provinsi: '35',
  },
  {
    kode_kabupaten: '1771',
    nama_kabupaten: 'KOTA BENGKULU',
    is_kota: 1,
    kode_provinsi: '17',
  },
  {
    kode_kabupaten: '3526',
    nama_kabupaten: 'BANGKALAN',
    is_kota: 0,
    kode_provinsi: '35',
  },
  {
    kode_kabupaten: '3525',
    nama_kabupaten: 'GRESIK',
    is_kota: 0,
    kode_provinsi: '35',
  },
  {
    kode_kabupaten: '3572',
    nama_kabupaten: 'KOTA BLITAR',
    is_kota: 1,
    kode_provinsi: '35',
  },
  {
    kode_kabupaten: '1805',
    nama_kabupaten: 'TULANG BAWANG',
    is_kota: 0,
    kode_provinsi: '18',
  },
  {
    kode_kabupaten: '3577',
    nama_kabupaten: 'KOTA MADIUN',
    is_kota: 1,
    kode_provinsi: '35',
  },
  {
    kode_kabupaten: '3571',
    nama_kabupaten: 'KOTA KEDIRI',
    is_kota: 1,
    kode_provinsi: '35',
  },
  {
    kode_kabupaten: '3603',
    nama_kabupaten: 'TANGERANG',
    is_kota: 0,
    kode_provinsi: '36',
  },
  {
    kode_kabupaten: '1810',
    nama_kabupaten: 'PRINGSEWU',
    is_kota: 0,
    kode_provinsi: '18',
  },
  {
    kode_kabupaten: '3674',
    nama_kabupaten: 'KOTA TANGERANG SELATAN',
    is_kota: 1,
    kode_provinsi: '36',
  },
  {
    kode_kabupaten: '3576',
    nama_kabupaten: 'KOTA MOJOKERTO',
    is_kota: 1,
    kode_provinsi: '35',
  },
  {
    kode_kabupaten: '5105',
    nama_kabupaten: 'KLUNGKUNG',
    is_kota: 0,
    kode_provinsi: '51',
  },
  {
    kode_kabupaten: '1872',
    nama_kabupaten: 'KOTA METRO',
    is_kota: 1,
    kode_provinsi: '18',
  },
  {
    kode_kabupaten: '5201',
    nama_kabupaten: 'LOMBOK BARAT',
    is_kota: 0,
    kode_provinsi: '52',
  },
  {
    kode_kabupaten: '3602',
    nama_kabupaten: 'LEBAK',
    is_kota: 0,
    kode_provinsi: '36',
  },
  {
    kode_kabupaten: '5206',
    nama_kabupaten: 'BIMA',
    is_kota: 0,
    kode_provinsi: '52',
  },
  {
    kode_kabupaten: '1905',
    nama_kabupaten: 'BANGKA BARAT',
    is_kota: 0,
    kode_provinsi: '19',
  },
  {
    kode_kabupaten: '5301',
    nama_kabupaten: 'KUPANG',
    is_kota: 0,
    kode_provinsi: '53',
  },
  {
    kode_kabupaten: '5306',
    nama_kabupaten: 'FLORES TIMUR',
    is_kota: 0,
    kode_provinsi: '53',
  },
  {
    kode_kabupaten: '3673',
    nama_kabupaten: 'KOTA SERANG',
    is_kota: 1,
    kode_provinsi: '36',
  },
  {
    kode_kabupaten: '5311',
    nama_kabupaten: 'SUMBA TIMUR',
    is_kota: 0,
    kode_provinsi: '53',
  },
  {
    kode_kabupaten: '2103',
    nama_kabupaten: 'NATUNA',
    is_kota: 0,
    kode_provinsi: '21',
  },
  {
    kode_kabupaten: '5316',
    nama_kabupaten: 'NAGEKEO',
    is_kota: 0,
    kode_provinsi: '53',
  },
  {
    kode_kabupaten: '5104',
    nama_kabupaten: 'GIANYAR',
    is_kota: 0,
    kode_provinsi: '51',
  },
  {
    kode_kabupaten: '5321',
    nama_kabupaten: 'MALAKA',
    is_kota: 0,
    kode_provinsi: '53',
  },
  {
    kode_kabupaten: '6104',
    nama_kabupaten: 'KETAPANG',
    is_kota: 0,
    kode_provinsi: '61',
  },
  {
    kode_kabupaten: '3101',
    nama_kabupaten: 'KEPULAUAN SERIBU',
    is_kota: 0,
    kode_provinsi: '31',
  },
  {
    kode_kabupaten: '6109',
    nama_kabupaten: 'SEKADAU',
    is_kota: 0,
    kode_provinsi: '61',
  },
  {
    kode_kabupaten: '5171',
    nama_kabupaten: 'KOTA DENPASAR',
    is_kota: 1,
    kode_provinsi: '51',
  },
  {
    kode_kabupaten: '6172',
    nama_kabupaten: 'KOTA SINGKAWANG',
    is_kota: 1,
    kode_provinsi: '61',
  },
  {
    kode_kabupaten: '6205',
    nama_kabupaten: 'BARITO UTARA',
    is_kota: 0,
    kode_provinsi: '62',
  },
  {
    kode_kabupaten: '3175',
    nama_kabupaten: 'KOTA ADM JAKARTA TIMUR',
    is_kota: 1,
    kode_provinsi: '31',
  },
  {
    kode_kabupaten: '6210',
    nama_kabupaten: 'GUNUNG MAS',
    is_kota: 0,
    kode_provinsi: '62',
  },
  {
    kode_kabupaten: '5205',
    nama_kabupaten: 'DOMPU',
    is_kota: 0,
    kode_provinsi: '52',
  },
  {
    kode_kabupaten: '6301',
    nama_kabupaten: 'TANAH LAUT',
    is_kota: 0,
    kode_provinsi: '63',
  },
  {
    kode_kabupaten: '6306',
    nama_kabupaten: 'HULU SUNGAI SELATAN',
    is_kota: 0,
    kode_provinsi: '63',
  },
  {
    kode_kabupaten: '3205',
    nama_kabupaten: 'GARUT',
    is_kota: 0,
    kode_provinsi: '32',
  },
  {
    kode_kabupaten: '6311',
    nama_kabupaten: 'BALANGAN',
    is_kota: 0,
    kode_provinsi: '63',
  },
  {
    kode_kabupaten: '5272',
    nama_kabupaten: 'KOTA BIMA',
    is_kota: 1,
    kode_provinsi: '52',
  },
  {
    kode_kabupaten: '6403',
    nama_kabupaten: 'BERAU',
    is_kota: 0,
    kode_provinsi: '64',
  },
  {
    kode_kabupaten: '6471',
    nama_kabupaten: 'KOTA BALIKPAPAN',
    is_kota: 1,
    kode_provinsi: '64',
  },
  {
    kode_kabupaten: '3210',
    nama_kabupaten: 'MAJALENGKA',
    is_kota: 0,
    kode_provinsi: '32',
  },
  {
    kode_kabupaten: '6503',
    nama_kabupaten: 'NUNUKAN',
    is_kota: 0,
    kode_provinsi: '65',
  },
  {
    kode_kabupaten: '5305',
    nama_kabupaten: 'ALOR',
    is_kota: 0,
    kode_provinsi: '53',
  },
  {
    kode_kabupaten: '7103',
    nama_kabupaten: 'KEPULAUAN SANGIHE',
    is_kota: 0,
    kode_provinsi: '71',
  },
  {
    kode_kabupaten: '7108',
    nama_kabupaten: 'BOLAANG MONGONDOW UTARA',
    is_kota: 0,
    kode_provinsi: '71',
  },
  {
    kode_kabupaten: '3215',
    nama_kabupaten: 'KARAWANG',
    is_kota: 0,
    kode_provinsi: '32',
  },
  {
    kode_kabupaten: '7172',
    nama_kabupaten: 'KOTA BITUNG',
    is_kota: 1,
    kode_provinsi: '71',
  },
  {
    kode_kabupaten: '5310',
    nama_kabupaten: 'MANGGARAI',
    is_kota: 0,
    kode_provinsi: '53',
  },
  {
    kode_kabupaten: '7203',
    nama_kabupaten: 'DONGGALA',
    is_kota: 0,
    kode_provinsi: '72',
  },
  {
    kode_kabupaten: '7208',
    nama_kabupaten: 'PARIGI MOUTONG',
    is_kota: 0,
    kode_provinsi: '72',
  },
  {
    kode_kabupaten: '3272',
    nama_kabupaten: 'KOTA SUKABUMI',
    is_kota: 1,
    kode_provinsi: '32',
  },
  {
    kode_kabupaten: '7271',
    nama_kabupaten: 'KOTA PALU',
    is_kota: 1,
    kode_provinsi: '72',
  },
  {
    kode_kabupaten: '5315',
    nama_kabupaten: 'MANGGARAI BARAT',
    is_kota: 0,
    kode_provinsi: '53',
  },
  {
    kode_kabupaten: '7305',
    nama_kabupaten: 'TAKALAR',
    is_kota: 0,
    kode_provinsi: '73',
  },
  {
    kode_kabupaten: '7310',
    nama_kabupaten: 'PANGKAJENE KEPULAUAN',
    is_kota: 0,
    kode_provinsi: '73',
  },
  {
    kode_kabupaten: '7315',
    nama_kabupaten: 'PINRANG',
    is_kota: 0,
    kode_provinsi: '73',
  },
  {
    kode_kabupaten: '5320',
    nama_kabupaten: 'SABU RAIJUA',
    is_kota: 0,
    kode_provinsi: '53',
  },
  {
    kode_kabupaten: '7324',
    nama_kabupaten: 'LUWU TIMUR',
    is_kota: 0,
    kode_provinsi: '73',
  },
  {
    kode_kabupaten: '6103',
    nama_kabupaten: 'SANGGAU',
    is_kota: 0,
    kode_provinsi: '61',
  },
  {
    kode_kabupaten: '7401',
    nama_kabupaten: 'KOLAKA',
    is_kota: 0,
    kode_provinsi: '74',
  },
  {
    kode_kabupaten: '7406',
    nama_kabupaten: 'BOMBANA',
    is_kota: 0,
    kode_provinsi: '74',
  },
  {
    kode_kabupaten: '6108',
    nama_kabupaten: 'LANDAK',
    is_kota: 0,
    kode_provinsi: '61',
  },
  {
    kode_kabupaten: '7411',
    nama_kabupaten: 'KOLAKA TIMUR',
    is_kota: 0,
    kode_provinsi: '74',
  },
  {
    kode_kabupaten: '7471',
    nama_kabupaten: 'KOTA KENDARI',
    is_kota: 1,
    kode_provinsi: '74',
  },
  {
    kode_kabupaten: '7504',
    nama_kabupaten: 'PAHUWATO',
    is_kota: 0,
    kode_provinsi: '75',
  },
  {
    kode_kabupaten: '7603',
    nama_kabupaten: 'MAMASA',
    is_kota: 0,
    kode_provinsi: '76',
  },
  {
    kode_kabupaten: '8102',
    nama_kabupaten: 'MALUKU TENGGARA',
    is_kota: 0,
    kode_provinsi: '81',
  },
  {
    kode_kabupaten: '8107',
    nama_kabupaten: 'KEPULAUAN ARU',
    is_kota: 0,
    kode_provinsi: '81',
  },
  {
    kode_kabupaten: '1206',
    nama_kabupaten: 'KARO',
    is_kota: 0,
    kode_provinsi: '12',
  },
  {
    kode_kabupaten: '8201',
    nama_kabupaten: 'HALMAHERA BARAT',
    is_kota: 0,
    kode_provinsi: '82',
  },
  {
    kode_kabupaten: '8206',
    nama_kabupaten: 'HALMAHERA TIMUR',
    is_kota: 0,
    kode_provinsi: '82',
  },
  {
    kode_kabupaten: '9101',
    nama_kabupaten: 'MERAUKE',
    is_kota: 0,
    kode_provinsi: '91',
  },
  {
    kode_kabupaten: '9106',
    nama_kabupaten: 'BIAK NUMFOR',
    is_kota: 0,
    kode_provinsi: '91',
  },
  {
    kode_kabupaten: '9111',
    nama_kabupaten: 'KEEROM',
    is_kota: 0,
    kode_provinsi: '91',
  },
  {
    kode_kabupaten: '9116',
    nama_kabupaten: 'BOVEN DIGOEL',
    is_kota: 0,
    kode_provinsi: '91',
  },
  {
    kode_kabupaten: '9121',
    nama_kabupaten: 'MAMBERAMO TENGAH',
    is_kota: 0,
    kode_provinsi: '91',
  },
  {
    kode_kabupaten: '9126',
    nama_kabupaten: 'DOGIYAI',
    is_kota: 0,
    kode_provinsi: '91',
  },
  {
    kode_kabupaten: '9202',
    nama_kabupaten: 'MANOKWARI',
    is_kota: 0,
    kode_provinsi: '92',
  },
  {
    kode_kabupaten: '9207',
    nama_kabupaten: 'TELUK WONDAMA',
    is_kota: 0,
    kode_provinsi: '92',
  },
  {
    kode_kabupaten: '9212',
    nama_kabupaten: 'PEGUNUNGAN ARFAK',
    is_kota: 0,
    kode_provinsi: '92',
  },
  {
    kode_kabupaten: '3277',
    nama_kabupaten: 'KOTA CIMAHI',
    is_kota: 1,
    kode_provinsi: '32',
  },
  {
    kode_kabupaten: '3303',
    nama_kabupaten: 'PURBALINGGA',
    is_kota: 0,
    kode_provinsi: '33',
  },
  {
    kode_kabupaten: '3308',
    nama_kabupaten: 'MAGELANG',
    is_kota: 0,
    kode_provinsi: '33',
  },
  {
    kode_kabupaten: '3313',
    nama_kabupaten: 'KARANGANYAR',
    is_kota: 0,
    kode_provinsi: '33',
  },
  {
    kode_kabupaten: '3318',
    nama_kabupaten: 'PATI',
    is_kota: 0,
    kode_provinsi: '33',
  },
  {
    kode_kabupaten: '3323',
    nama_kabupaten: 'TEMANGGUNG',
    is_kota: 0,
    kode_provinsi: '33',
  },
  {
    kode_kabupaten: '1211',
    nama_kabupaten: 'DAIRI',
    is_kota: 0,
    kode_provinsi: '12',
  },
  {
    kode_kabupaten: '3328',
    nama_kabupaten: 'TEGAL',
    is_kota: 0,
    kode_provinsi: '33',
  },
  {
    kode_kabupaten: '1216',
    nama_kabupaten: 'HUMBANG HASUNDUTAN',
    is_kota: 0,
    kode_provinsi: '12',
  },
  {
    kode_kabupaten: '3374',
    nama_kabupaten: 'KOTA SEMARANG',
    is_kota: 1,
    kode_provinsi: '33',
  },
  {
    kode_kabupaten: '1221',
    nama_kabupaten: 'PADANG LAWAS',
    is_kota: 0,
    kode_provinsi: '12',
  },
  {
    kode_kabupaten: '3403',
    nama_kabupaten: 'GUNUNGKIDUL',
    is_kota: 0,
    kode_provinsi: '34',
  },
  {
    kode_kabupaten: '1271',
    nama_kabupaten: 'KOTA MEDAN',
    is_kota: 1,
    kode_provinsi: '12',
  },
  {
    kode_kabupaten: '3503',
    nama_kabupaten: 'TRENGGALEK',
    is_kota: 0,
    kode_provinsi: '35',
  },
  {
    kode_kabupaten: '1276',
    nama_kabupaten: 'KOTA TEBING TINGGI',
    is_kota: 1,
    kode_provinsi: '12',
  },
  {
    kode_kabupaten: '1303',
    nama_kabupaten: 'SIJUNJUNG',
    is_kota: 0,
    kode_provinsi: '13',
  },
  {
    kode_kabupaten: '3508',
    nama_kabupaten: 'LUMAJANG',
    is_kota: 0,
    kode_provinsi: '35',
  },
  {
    kode_kabupaten: '1308',
    nama_kabupaten: 'PASAMAN',
    is_kota: 0,
    kode_provinsi: '13',
  },
  {
    kode_kabupaten: '3513',
    nama_kabupaten: 'PROBOLINGGO',
    is_kota: 0,
    kode_provinsi: '35',
  },
  {
    kode_kabupaten: '1371',
    nama_kabupaten: 'KOTA PADANG',
    is_kota: 1,
    kode_provinsi: '13',
  },
  {
    kode_kabupaten: '3518',
    nama_kabupaten: 'NGANJUK',
    is_kota: 0,
    kode_provinsi: '35',
  },
  {
    kode_kabupaten: '1376',
    nama_kabupaten: 'KOTA PAYAKUMBUH',
    is_kota: 1,
    kode_provinsi: '13',
  },
  {
    kode_kabupaten: '3523',
    nama_kabupaten: 'TUBAN',
    is_kota: 0,
    kode_provinsi: '35',
  },
  {
    kode_kabupaten: '1404',
    nama_kabupaten: 'INDRAGIRI HILIR',
    is_kota: 0,
    kode_provinsi: '14',
  },
  {
    kode_kabupaten: '3528',
    nama_kabupaten: 'PAMEKASAN',
    is_kota: 0,
    kode_provinsi: '35',
  },
  {
    kode_kabupaten: '1409',
    nama_kabupaten: 'KUANTAN SINGINGI',
    is_kota: 0,
    kode_provinsi: '14',
  },
  {
    kode_kabupaten: '3574',
    nama_kabupaten: 'KOTA PROBOLINGGO',
    is_kota: 1,
    kode_provinsi: '35',
  },
  {
    kode_kabupaten: '1502',
    nama_kabupaten: 'MERANGIN',
    is_kota: 0,
    kode_provinsi: '15',
  },
  {
    kode_kabupaten: '3579',
    nama_kabupaten: 'KOTA BATU',
    is_kota: 1,
    kode_provinsi: '35',
  },
  {
    kode_kabupaten: '1507',
    nama_kabupaten: 'TANJUNG JABUNG TIMUR',
    is_kota: 0,
    kode_provinsi: '15',
  },
  {
    kode_kabupaten: '3671',
    nama_kabupaten: 'KOTA TANGERANG',
    is_kota: 1,
    kode_provinsi: '36',
  },
  {
    kode_kabupaten: '1601',
    nama_kabupaten: 'OGAN KOMERING ULU',
    is_kota: 0,
    kode_provinsi: '16',
  },
  {
    kode_kabupaten: '5102',
    nama_kabupaten: 'TABANAN',
    is_kota: 0,
    kode_provinsi: '51',
  },
  {
    kode_kabupaten: '1606',
    nama_kabupaten: 'MUSI BANYUASIN',
    is_kota: 0,
    kode_provinsi: '16',
  },
  {
    kode_kabupaten: '5107',
    nama_kabupaten: 'KARANGASEM',
    is_kota: 0,
    kode_provinsi: '51',
  },
  {
    kode_kabupaten: '1611',
    nama_kabupaten: 'EMPAT LAWANG',
    is_kota: 0,
    kode_provinsi: '16',
  },
  {
    kode_kabupaten: '5203',
    nama_kabupaten: 'LOMBOK TIMUR',
    is_kota: 0,
    kode_provinsi: '52',
  },
  {
    kode_kabupaten: '1673',
    nama_kabupaten: 'KOTA LUBUK LINGGAU',
    is_kota: 1,
    kode_provinsi: '16',
  },
  {
    kode_kabupaten: '5208',
    nama_kabupaten: 'LOMBOK UTARA',
    is_kota: 0,
    kode_provinsi: '52',
  },
  {
    kode_kabupaten: '1704',
    nama_kabupaten: 'KAUR',
    is_kota: 0,
    kode_provinsi: '17',
  },
  {
    kode_kabupaten: '5303',
    nama_kabupaten: 'TIMOR TENGAH UTARA',
    is_kota: 0,
    kode_provinsi: '53',
  },
  {
    kode_kabupaten: '1709',
    nama_kabupaten: 'BENGKULU TENGAH',
    is_kota: 0,
    kode_provinsi: '17',
  },
  {
    kode_kabupaten: '5308',
    nama_kabupaten: 'ENDE',
    is_kota: 0,
    kode_provinsi: '53',
  },
  {
    kode_kabupaten: '1804',
    nama_kabupaten: 'LAMPUNG BARAT',
    is_kota: 0,
    kode_provinsi: '18',
  },
  {
    kode_kabupaten: '1809',
    nama_kabupaten: 'PESAWARAN',
    is_kota: 0,
    kode_provinsi: '18',
  },
  {
    kode_kabupaten: '5313',
    nama_kabupaten: 'LEMBATA',
    is_kota: 0,
    kode_provinsi: '53',
  },
  {
    kode_kabupaten: '1871',
    nama_kabupaten: 'KOTA BANDAR LAMPUNG',
    is_kota: 1,
    kode_provinsi: '18',
  },
  {
    kode_kabupaten: '5318',
    nama_kabupaten: 'SUMBA BARAT DAYA',
    is_kota: 0,
    kode_provinsi: '53',
  },
  {
    kode_kabupaten: '1904',
    nama_kabupaten: 'BANGKA TENGAH',
    is_kota: 0,
    kode_provinsi: '19',
  },
  {
    kode_kabupaten: '6101',
    nama_kabupaten: 'SAMBAS',
    is_kota: 0,
    kode_provinsi: '61',
  },
  {
    kode_kabupaten: '2102',
    nama_kabupaten: 'KARIMUN',
    is_kota: 0,
    kode_provinsi: '21',
  },
  {
    kode_kabupaten: '6106',
    nama_kabupaten: 'KAPUAS HULU',
    is_kota: 0,
    kode_provinsi: '61',
  },
  {
    kode_kabupaten: '2172',
    nama_kabupaten: 'KOTA TANJUNG PINANG',
    is_kota: 1,
    kode_provinsi: '21',
  },
  {
    kode_kabupaten: '6111',
    nama_kabupaten: 'KAYONG UTARA',
    is_kota: 0,
    kode_provinsi: '61',
  },
  {
    kode_kabupaten: '3174',
    nama_kabupaten: 'KOTA ADM JAKARTA SELATAN',
    is_kota: 1,
    kode_provinsi: '31',
  },
  {
    kode_kabupaten: '6202',
    nama_kabupaten: 'KOTAWARINGIN TIMUR',
    is_kota: 0,
    kode_provinsi: '62',
  },
  {
    kode_kabupaten: '3204',
    nama_kabupaten: 'BANDUNG',
    is_kota: 0,
    kode_provinsi: '32',
  },
  {
    kode_kabupaten: '6207',
    nama_kabupaten: 'SERUYAN',
    is_kota: 0,
    kode_provinsi: '62',
  },
  {
    kode_kabupaten: '3209',
    nama_kabupaten: 'CIREBON',
    is_kota: 0,
    kode_provinsi: '32',
  },
  {
    kode_kabupaten: '6212',
    nama_kabupaten: 'MURUNG RAYA',
    is_kota: 0,
    kode_provinsi: '62',
  },
  {
    kode_kabupaten: '3214',
    nama_kabupaten: 'PURWAKARTA',
    is_kota: 0,
    kode_provinsi: '32',
  },
  {
    kode_kabupaten: '6303',
    nama_kabupaten: 'BANJAR',
    is_kota: 0,
    kode_provinsi: '63',
  },
  {
    kode_kabupaten: '3271',
    nama_kabupaten: 'KOTA BOGOR',
    is_kota: 1,
    kode_provinsi: '32',
  },
  {
    kode_kabupaten: '3276',
    nama_kabupaten: 'KOTA DEPOK',
    is_kota: 1,
    kode_provinsi: '32',
  },
  {
    kode_kabupaten: '6308',
    nama_kabupaten: 'HULU SUNGAI UTARA',
    is_kota: 0,
    kode_provinsi: '63',
  },
  {
    kode_kabupaten: '3302',
    nama_kabupaten: 'BANYUMAS',
    is_kota: 0,
    kode_provinsi: '33',
  },
  {
    kode_kabupaten: '6372',
    nama_kabupaten: 'KOTA BANJARBARU',
    is_kota: 1,
    kode_provinsi: '63',
  },
  {
    kode_kabupaten: '3307',
    nama_kabupaten: 'WONOSOBO',
    is_kota: 0,
    kode_provinsi: '33',
  },
  {
    kode_kabupaten: '6408',
    nama_kabupaten: 'KUTAI TIMUR',
    is_kota: 0,
    kode_provinsi: '64',
  },
  {
    kode_kabupaten: '3312',
    nama_kabupaten: 'WONOGIRI',
    is_kota: 0,
    kode_provinsi: '33',
  },
  {
    kode_kabupaten: '6474',
    nama_kabupaten: 'KOTA BONTANG',
    is_kota: 1,
    kode_provinsi: '64',
  },
  {
    kode_kabupaten: '3317',
    nama_kabupaten: 'REMBANG',
    is_kota: 0,
    kode_provinsi: '33',
  },
  {
    kode_kabupaten: '6571',
    nama_kabupaten: 'KOTA TARAKAN',
    is_kota: 1,
    kode_provinsi: '65',
  },
  {
    kode_kabupaten: '3322',
    nama_kabupaten: 'SEMARANG',
    is_kota: 0,
    kode_provinsi: '33',
  },
  {
    kode_kabupaten: '7105',
    nama_kabupaten: 'MINAHASA SELATAN',
    is_kota: 0,
    kode_provinsi: '71',
  },
  {
    kode_kabupaten: '3327',
    nama_kabupaten: 'PEMALANG',
    is_kota: 0,
    kode_provinsi: '33',
  },
  {
    kode_kabupaten: '7110',
    nama_kabupaten: 'BOLAANG MONGONDOW TIMUR',
    is_kota: 0,
    kode_provinsi: '71',
  },
  {
    kode_kabupaten: '3373',
    nama_kabupaten: 'KOTA SALATIGA',
    is_kota: 1,
    kode_provinsi: '33',
  },
  {
    kode_kabupaten: '7174',
    nama_kabupaten: 'KOTA KOTAMOBAGU',
    is_kota: 1,
    kode_provinsi: '71',
  },
  {
    kode_kabupaten: '3402',
    nama_kabupaten: 'BANTUL',
    is_kota: 0,
    kode_provinsi: '34',
  },
  {
    kode_kabupaten: '3502',
    nama_kabupaten: 'PONOROGO',
    is_kota: 0,
    kode_provinsi: '35',
  },
  {
    kode_kabupaten: '7205',
    nama_kabupaten: 'BUOL',
    is_kota: 0,
    kode_provinsi: '72',
  },
  {
    kode_kabupaten: '7210',
    nama_kabupaten: 'SIGI',
    is_kota: 0,
    kode_provinsi: '72',
  },
  {
    kode_kabupaten: '3507',
    nama_kabupaten: 'MALANG',
    is_kota: 0,
    kode_provinsi: '35',
  },
  {
    kode_kabupaten: '3512',
    nama_kabupaten: 'SITUBONDO',
    is_kota: 0,
    kode_provinsi: '35',
  },
  {
    kode_kabupaten: '7302',
    nama_kabupaten: 'BULUKUMBA',
    is_kota: 0,
    kode_provinsi: '73',
  },
  {
    kode_kabupaten: '7307',
    nama_kabupaten: 'SINJAI',
    is_kota: 0,
    kode_provinsi: '73',
  },
  {
    kode_kabupaten: '7312',
    nama_kabupaten: 'SOPPENG',
    is_kota: 0,
    kode_provinsi: '73',
  },
  {
    kode_kabupaten: '7317',
    nama_kabupaten: 'LUWU',
    is_kota: 0,
    kode_provinsi: '73',
  },
  {
    kode_kabupaten: '7371',
    nama_kabupaten: 'KOTA MAKASSAR',
    is_kota: 1,
    kode_provinsi: '73',
  },
  {
    kode_kabupaten: '7403',
    nama_kabupaten: 'MUNA',
    is_kota: 0,
    kode_provinsi: '74',
  },
  {
    kode_kabupaten: '7408',
    nama_kabupaten: 'KOLAKA UTARA',
    is_kota: 0,
    kode_provinsi: '74',
  },
  {
    kode_kabupaten: '7413',
    nama_kabupaten: 'MUNA BARAT',
    is_kota: 0,
    kode_provinsi: '74',
  },
  {
    kode_kabupaten: '7501',
    nama_kabupaten: 'GORONTALO',
    is_kota: 0,
    kode_provinsi: '75',
  },
  {
    kode_kabupaten: '7571',
    nama_kabupaten: 'KOTA GORONTALO',
    is_kota: 1,
    kode_provinsi: '75',
  },
  {
    kode_kabupaten: '7605',
    nama_kabupaten: 'MAJENE',
    is_kota: 0,
    kode_provinsi: '76',
  },
  {
    kode_kabupaten: '6171',
    nama_kabupaten: 'KOTA PONTIANAK',
    is_kota: 1,
    kode_provinsi: '61',
  },
  {
    kode_kabupaten: '8104',
    nama_kabupaten: 'BURU',
    is_kota: 0,
    kode_provinsi: '81',
  },
  {
    kode_kabupaten: '6204',
    nama_kabupaten: 'BARITO SELATAN',
    is_kota: 0,
    kode_provinsi: '62',
  },
  {
    kode_kabupaten: '6209',
    nama_kabupaten: 'LAMANDAU',
    is_kota: 0,
    kode_provinsi: '62',
  },
  {
    kode_kabupaten: '8109',
    nama_kabupaten: 'BURU SELATAN',
    is_kota: 0,
    kode_provinsi: '81',
  },
  {
    kode_kabupaten: '6271',
    nama_kabupaten: 'KOTA PALANGKARAYA',
    is_kota: 1,
    kode_provinsi: '62',
  },
  {
    kode_kabupaten: '8203',
    nama_kabupaten: 'HALMAHERA UTARA',
    is_kota: 0,
    kode_provinsi: '82',
  },
  {
    kode_kabupaten: '6305',
    nama_kabupaten: 'TAPIN',
    is_kota: 0,
    kode_provinsi: '63',
  },
  {
    kode_kabupaten: '8208',
    nama_kabupaten: 'PULAU TALIABU',
    is_kota: 0,
    kode_provinsi: '82',
  },
  {
    kode_kabupaten: '6310',
    nama_kabupaten: 'TANAH BUMBU',
    is_kota: 0,
    kode_provinsi: '63',
  },
  {
    kode_kabupaten: '6402',
    nama_kabupaten: 'KUTAI KARTANEGARA',
    is_kota: 0,
    kode_provinsi: '64',
  },
  {
    kode_kabupaten: '9103',
    nama_kabupaten: 'JAYAPURA',
    is_kota: 0,
    kode_provinsi: '91',
  },
  {
    kode_kabupaten: '6411',
    nama_kabupaten: 'MAHAKAM ULU',
    is_kota: 0,
    kode_provinsi: '64',
  },
  {
    kode_kabupaten: '9108',
    nama_kabupaten: 'PANIAI',
    is_kota: 0,
    kode_provinsi: '91',
  },
  {
    kode_kabupaten: '6502',
    nama_kabupaten: 'MALINAU',
    is_kota: 0,
    kode_provinsi: '65',
  },
  {
    kode_kabupaten: '7102',
    nama_kabupaten: 'MINAHASA',
    is_kota: 0,
    kode_provinsi: '71',
  },
  {
    kode_kabupaten: '9113',
    nama_kabupaten: 'YAHUKIMO',
    is_kota: 0,
    kode_provinsi: '91',
  },
  {
    kode_kabupaten: '7107',
    nama_kabupaten: 'MINAHASA TENGGARA',
    is_kota: 0,
    kode_provinsi: '71',
  },
  {
    kode_kabupaten: '9118',
    nama_kabupaten: 'ASMAT',
    is_kota: 0,
    kode_provinsi: '91',
  },
  {
    kode_kabupaten: '7171',
    nama_kabupaten: 'KOTA MANADO',
    is_kota: 1,
    kode_provinsi: '71',
  },
  {
    kode_kabupaten: '7202',
    nama_kabupaten: 'POSO',
    is_kota: 0,
    kode_provinsi: '72',
  },
  {
    kode_kabupaten: '9123',
    nama_kabupaten: 'LANNY JAYA',
    is_kota: 0,
    kode_provinsi: '91',
  },
  {
    kode_kabupaten: '7207',
    nama_kabupaten: 'BANGGAI KEPULAUAN',
    is_kota: 0,
    kode_provinsi: '72',
  },
  {
    kode_kabupaten: '9128',
    nama_kabupaten: 'DEIYAI',
    is_kota: 0,
    kode_provinsi: '91',
  },
  {
    kode_kabupaten: '7212',
    nama_kabupaten: 'MOROWALI UTARA',
    is_kota: 0,
    kode_provinsi: '72',
  },
  {
    kode_kabupaten: '9204',
    nama_kabupaten: 'SORONG SELATAN',
    is_kota: 0,
    kode_provinsi: '92',
  },
  {
    kode_kabupaten: '7304',
    nama_kabupaten: 'JENEPONTO',
    is_kota: 0,
    kode_provinsi: '73',
  },
  {
    kode_kabupaten: '7309',
    nama_kabupaten: 'MAROS',
    is_kota: 0,
    kode_provinsi: '73',
  },
  {
    kode_kabupaten: '9209',
    nama_kabupaten: 'TAMBRAUW',
    is_kota: 0,
    kode_provinsi: '92',
  },
  {
    kode_kabupaten: '7314',
    nama_kabupaten: 'SIDENRENG RAPPANG',
    is_kota: 0,
    kode_provinsi: '73',
  },
  {
    kode_kabupaten: '7322',
    nama_kabupaten: 'LUWU UTARA',
    is_kota: 0,
    kode_provinsi: '73',
  },
  {
    kode_kabupaten: '7373',
    nama_kabupaten: 'KOTA PALOPO',
    is_kota: 1,
    kode_provinsi: '73',
  },
  {
    kode_kabupaten: '7405',
    nama_kabupaten: 'KONAWE SELATAN',
    is_kota: 0,
    kode_provinsi: '74',
  },
  {
    kode_kabupaten: '3171',
    nama_kabupaten: 'KOTA ADM JAKARTA PUSAT',
    is_kota: 1,
    kode_provinsi: '31',
  },
  {
    kode_kabupaten: '3517',
    nama_kabupaten: 'JOMBANG',
    is_kota: 0,
    kode_provinsi: '35',
  },
  {
    kode_kabupaten: '3522',
    nama_kabupaten: 'BOJONEGORO',
    is_kota: 0,
    kode_provinsi: '35',
  },
  {
    kode_kabupaten: '3527',
    nama_kabupaten: 'SAMPANG',
    is_kota: 0,
    kode_provinsi: '35',
  },
  {
    kode_kabupaten: '3573',
    nama_kabupaten: 'KOTA MALANG',
    is_kota: 1,
    kode_provinsi: '35',
  },
  {
    kode_kabupaten: '3578',
    nama_kabupaten: 'KOTA SURABAYA',
    is_kota: 1,
    kode_provinsi: '35',
  },
  {
    kode_kabupaten: '3604',
    nama_kabupaten: 'SERANG',
    is_kota: 0,
    kode_provinsi: '36',
  },
  {
    kode_kabupaten: '5101',
    nama_kabupaten: 'JEMBRANA',
    is_kota: 0,
    kode_provinsi: '51',
  },
  {
    kode_kabupaten: '5106',
    nama_kabupaten: 'BANGLI',
    is_kota: 0,
    kode_provinsi: '51',
  },
  {
    kode_kabupaten: '5202',
    nama_kabupaten: 'LOMBOK TENGAH',
    is_kota: 0,
    kode_provinsi: '52',
  },
  {
    kode_kabupaten: '5207',
    nama_kabupaten: 'SUMBAWA BARAT',
    is_kota: 0,
    kode_provinsi: '52',
  },
  {
    kode_kabupaten: '5302',
    nama_kabupaten: 'KAB TIMOR TENGAH SELATAN',
    is_kota: 0,
    kode_provinsi: '53',
  },
  {
    kode_kabupaten: '5307',
    nama_kabupaten: 'SIKKA',
    is_kota: 0,
    kode_provinsi: '53',
  },
  {
    kode_kabupaten: '5312',
    nama_kabupaten: 'SUMBA BARAT',
    is_kota: 0,
    kode_provinsi: '53',
  },
  {
    kode_kabupaten: '5317',
    nama_kabupaten: 'SUMBA TENGAH',
    is_kota: 0,
    kode_provinsi: '53',
  },
  {
    kode_kabupaten: '5371',
    nama_kabupaten: 'KOTA KUPANG',
    is_kota: 1,
    kode_provinsi: '53',
  },
  {
    kode_kabupaten: '6105',
    nama_kabupaten: 'SINTANG',
    is_kota: 0,
    kode_provinsi: '61',
  },
  {
    kode_kabupaten: '6110',
    nama_kabupaten: 'MELAWI',
    is_kota: 0,
    kode_provinsi: '61',
  },
  {
    kode_kabupaten: '6201',
    nama_kabupaten: 'KOTAWARINGIN BARAT',
    is_kota: 0,
    kode_provinsi: '62',
  },
  {
    kode_kabupaten: '6206',
    nama_kabupaten: 'KATINGAN',
    is_kota: 0,
    kode_provinsi: '62',
  },
  {
    kode_kabupaten: '6211',
    nama_kabupaten: 'PULANG PISAU',
    is_kota: 0,
    kode_provinsi: '62',
  },
  {
    kode_kabupaten: '6302',
    nama_kabupaten: 'KOTABARU',
    is_kota: 0,
    kode_provinsi: '63',
  },
  {
    kode_kabupaten: '6307',
    nama_kabupaten: 'HULU SUNGAI TENGAH',
    is_kota: 0,
    kode_provinsi: '63',
  },
  {
    kode_kabupaten: '6371',
    nama_kabupaten: 'KOTA BANJARMASIN',
    is_kota: 1,
    kode_provinsi: '63',
  },
  {
    kode_kabupaten: '6407',
    nama_kabupaten: 'KUTAI BARAT',
    is_kota: 0,
    kode_provinsi: '64',
  },
  {
    kode_kabupaten: '6472',
    nama_kabupaten: 'KOTA SAMARINDA',
    is_kota: 1,
    kode_provinsi: '64',
  },
  {
    kode_kabupaten: '6504',
    nama_kabupaten: 'TANA TIDUNG',
    is_kota: 0,
    kode_provinsi: '65',
  },
  {
    kode_kabupaten: '7104',
    nama_kabupaten: 'KEPULAUAN TALAUD',
    is_kota: 0,
    kode_provinsi: '71',
  },
  {
    kode_kabupaten: '7109',
    nama_kabupaten: 'KEPULAUAN SIAU TAGULANDANG BIARO',
    is_kota: 0,
    kode_provinsi: '71',
  },
  {
    kode_kabupaten: '7173',
    nama_kabupaten: 'KOTA TOMOHON',
    is_kota: 1,
    kode_provinsi: '71',
  },
  {
    kode_kabupaten: '7204',
    nama_kabupaten: 'TOLI TOLI',
    is_kota: 0,
    kode_provinsi: '72',
  },
  {
    kode_kabupaten: '7209',
    nama_kabupaten: 'TOJO UNA UNA',
    is_kota: 0,
    kode_provinsi: '72',
  },
  {
    kode_kabupaten: '7301',
    nama_kabupaten: 'KEPULAUAN SELAYAR',
    is_kota: 0,
    kode_provinsi: '73',
  },
  {
    kode_kabupaten: '7306',
    nama_kabupaten: 'GOWA',
    is_kota: 0,
    kode_provinsi: '73',
  },
  {
    kode_kabupaten: '7311',
    nama_kabupaten: 'BARRU',
    is_kota: 0,
    kode_provinsi: '73',
  },
  {
    kode_kabupaten: '7316',
    nama_kabupaten: 'ENREKANG',
    is_kota: 0,
    kode_provinsi: '73',
  },
  {
    kode_kabupaten: '7326',
    nama_kabupaten: 'TORAJA UTARA',
    is_kota: 0,
    kode_provinsi: '73',
  },
  {
    kode_kabupaten: '7402',
    nama_kabupaten: 'KONAWE',
    is_kota: 0,
    kode_provinsi: '74',
  },
  {
    kode_kabupaten: '7407',
    nama_kabupaten: 'WAKATOBI',
    is_kota: 0,
    kode_provinsi: '74',
  },
  {
    kode_kabupaten: '7412',
    nama_kabupaten: 'KONAWE KEPULAUAN',
    is_kota: 0,
    kode_provinsi: '74',
  },
  {
    kode_kabupaten: '7472',
    nama_kabupaten: 'KOTA BAU BAU',
    is_kota: 1,
    kode_provinsi: '74',
  },
  {
    kode_kabupaten: '7505',
    nama_kabupaten: 'GORONTALO UTARA',
    is_kota: 0,
    kode_provinsi: '75',
  },
  {
    kode_kabupaten: '7604',
    nama_kabupaten: 'POLEWALI MANDAR',
    is_kota: 0,
    kode_provinsi: '76',
  },
  {
    kode_kabupaten: '7410',
    nama_kabupaten: 'BUTON UTARA',
    is_kota: 0,
    kode_provinsi: '74',
  },
  {
    kode_kabupaten: '7415',
    nama_kabupaten: 'BUTON SELATAN',
    is_kota: 0,
    kode_provinsi: '74',
  },
  {
    kode_kabupaten: '7503',
    nama_kabupaten: 'BONE BOLANGO',
    is_kota: 0,
    kode_provinsi: '75',
  },
  {
    kode_kabupaten: '7602',
    nama_kabupaten: 'MAMUJU',
    is_kota: 0,
    kode_provinsi: '76',
  },
  {
    kode_kabupaten: '8101',
    nama_kabupaten: 'MALUKU TENGAH',
    is_kota: 0,
    kode_provinsi: '81',
  },
  {
    kode_kabupaten: '8106',
    nama_kabupaten: 'SERAM BAGIAN BARAT',
    is_kota: 0,
    kode_provinsi: '81',
  },
  {
    kode_kabupaten: '8172',
    nama_kabupaten: 'KOTA TUAL',
    is_kota: 1,
    kode_provinsi: '81',
  },
  {
    kode_kabupaten: '8205',
    nama_kabupaten: 'KEPULAUAN SULA',
    is_kota: 0,
    kode_provinsi: '82',
  },
  {
    kode_kabupaten: '8272',
    nama_kabupaten: 'KOTA TIDORE KEPULAUAN',
    is_kota: 1,
    kode_provinsi: '82',
  },
  {
    kode_kabupaten: '9105',
    nama_kabupaten: 'KEPULAUAN YAPEN',
    is_kota: 0,
    kode_provinsi: '91',
  },
  {
    kode_kabupaten: '9110',
    nama_kabupaten: 'SARMI',
    is_kota: 0,
    kode_provinsi: '91',
  },
  {
    kode_kabupaten: '9115',
    nama_kabupaten: 'WAROPEN',
    is_kota: 0,
    kode_provinsi: '91',
  },
  {
    kode_kabupaten: '9120',
    nama_kabupaten: 'MAMBERAMO RAYA',
    is_kota: 0,
    kode_provinsi: '91',
  },
  {
    kode_kabupaten: '9125',
    nama_kabupaten: 'PUNCAK',
    is_kota: 0,
    kode_provinsi: '91',
  },
  {
    kode_kabupaten: '9201',
    nama_kabupaten: 'SORONG',
    is_kota: 0,
    kode_provinsi: '92',
  },
  {
    kode_kabupaten: '9206',
    nama_kabupaten: 'TELUK BINTUNI',
    is_kota: 0,
    kode_provinsi: '92',
  },
  {
    kode_kabupaten: '9211',
    nama_kabupaten: 'MANOKWARI SELATAN',
    is_kota: 0,
    kode_provinsi: '92',
  },
  {
    kode_kabupaten: '8103',
    nama_kabupaten: 'MALUKU TENGGARA BARAT',
    is_kota: 0,
    kode_provinsi: '81',
  },
  {
    kode_kabupaten: '8108',
    nama_kabupaten: 'MALUKU BARAT DAYA',
    is_kota: 0,
    kode_provinsi: '81',
  },
  {
    kode_kabupaten: '8202',
    nama_kabupaten: 'HALMAHERA TENGAH',
    is_kota: 0,
    kode_provinsi: '82',
  },
  {
    kode_kabupaten: '8207',
    nama_kabupaten: 'PULAU MOROTAI',
    is_kota: 0,
    kode_provinsi: '82',
  },
  {
    kode_kabupaten: '9102',
    nama_kabupaten: 'JAYAWIJAYA',
    is_kota: 0,
    kode_provinsi: '91',
  },
  {
    kode_kabupaten: '9107',
    nama_kabupaten: 'PUNCAK JAYA',
    is_kota: 0,
    kode_provinsi: '91',
  },
  {
    kode_kabupaten: '9112',
    nama_kabupaten: 'PEGUNUNGAN BINTANG',
    is_kota: 0,
    kode_provinsi: '91',
  },
  {
    kode_kabupaten: '9117',
    nama_kabupaten: 'MAPPI',
    is_kota: 0,
    kode_provinsi: '91',
  },
  {
    kode_kabupaten: '9122',
    nama_kabupaten: 'YALIMO',
    is_kota: 0,
    kode_provinsi: '91',
  },
  {
    kode_kabupaten: '9127',
    nama_kabupaten: 'INTAN JAYA',
    is_kota: 0,
    kode_provinsi: '91',
  },
  {
    kode_kabupaten: '9203',
    nama_kabupaten: 'FAK FAK',
    is_kota: 0,
    kode_provinsi: '92',
  },
  {
    kode_kabupaten: '9208',
    nama_kabupaten: 'KAIMANA',
    is_kota: 0,
    kode_provinsi: '92',
  },
  {
    kode_kabupaten: '9271',
    nama_kabupaten: 'KOTA SORONG',
    is_kota: 1,
    kode_provinsi: '92',
  },
  {
    kode_kabupaten: '3201',
    nama_kabupaten: 'BOGOR',
    is_kota: 0,
    kode_provinsi: '32',
  },
  {
    kode_kabupaten: '3206',
    nama_kabupaten: 'TASIKMALAYA',
    is_kota: 0,
    kode_provinsi: '32',
  },
  {
    kode_kabupaten: '3211',
    nama_kabupaten: 'SUMEDANG',
    is_kota: 0,
    kode_provinsi: '32',
  },
  {
    kode_kabupaten: '3216',
    nama_kabupaten: 'BEKASI',
    is_kota: 0,
    kode_provinsi: '32',
  },
  {
    kode_kabupaten: '3273',
    nama_kabupaten: 'KOTA BANDUNG',
    is_kota: 1,
    kode_provinsi: '32',
  },
  {
    kode_kabupaten: '3278',
    nama_kabupaten: 'KOTA TASIKMALAYA',
    is_kota: 1,
    kode_provinsi: '32',
  },
  {
    kode_kabupaten: '3304',
    nama_kabupaten: 'BANJARNEGARA',
    is_kota: 0,
    kode_provinsi: '33',
  },
  {
    kode_kabupaten: '3309',
    nama_kabupaten: 'BOYOLALI',
    is_kota: 0,
    kode_provinsi: '33',
  },
  {
    kode_kabupaten: '3314',
    nama_kabupaten: 'SRAGEN',
    is_kota: 0,
    kode_provinsi: '33',
  },
  {
    kode_kabupaten: '3319',
    nama_kabupaten: 'KUDUS',
    is_kota: 0,
    kode_provinsi: '33',
  },
  {
    kode_kabupaten: '3324',
    nama_kabupaten: 'KENDAL',
    is_kota: 0,
    kode_provinsi: '33',
  },
  {
    kode_kabupaten: '3329',
    nama_kabupaten: 'BREBES',
    is_kota: 0,
    kode_provinsi: '33',
  },
  {
    kode_kabupaten: '3375',
    nama_kabupaten: 'KOTA PEKALONGAN',
    is_kota: 1,
    kode_provinsi: '33',
  },
  {
    kode_kabupaten: '3404',
    nama_kabupaten: 'SLEMAN',
    is_kota: 0,
    kode_provinsi: '34',
  },
  {
    kode_kabupaten: '3504',
    nama_kabupaten: 'TULUNGAGUNG',
    is_kota: 0,
    kode_provinsi: '35',
  },
  {
    kode_kabupaten: '3509',
    nama_kabupaten: 'JEMBER',
    is_kota: 0,
    kode_provinsi: '35',
  },
  {
    kode_kabupaten: '3514',
    nama_kabupaten: 'PASURUAN',
    is_kota: 0,
    kode_provinsi: '35',
  },
  {
    kode_kabupaten: '3519',
    nama_kabupaten: 'MADIUN',
    is_kota: 0,
    kode_provinsi: '35',
  },
  {
    kode_kabupaten: '3524',
    nama_kabupaten: 'LAMONGAN',
    is_kota: 0,
    kode_provinsi: '35',
  },
  {
    kode_kabupaten: '3529',
    nama_kabupaten: 'SUMENEP',
    is_kota: 0,
    kode_provinsi: '35',
  },
  {
    kode_kabupaten: '3575',
    nama_kabupaten: 'KOTA PASURUAN',
    is_kota: 1,
    kode_provinsi: '35',
  },
  {
    kode_kabupaten: '3601',
    nama_kabupaten: 'PANDEGLANG',
    is_kota: 0,
    kode_provinsi: '36',
  },
  {
    kode_kabupaten: '3672',
    nama_kabupaten: 'KOTA CILEGON',
    is_kota: 1,
    kode_provinsi: '36',
  },
  {
    kode_kabupaten: '5103',
    nama_kabupaten: 'BADUNG',
    is_kota: 0,
    kode_provinsi: '51',
  },
  {
    kode_kabupaten: '5108',
    nama_kabupaten: 'BULELENG',
    is_kota: 0,
    kode_provinsi: '51',
  },
  {
    kode_kabupaten: '5204',
    nama_kabupaten: 'SUMBAWA',
    is_kota: 0,
    kode_provinsi: '52',
  },
  {
    kode_kabupaten: '5271',
    nama_kabupaten: 'KOTA MATARAM',
    is_kota: 1,
    kode_provinsi: '52',
  },
  {
    kode_kabupaten: '5304',
    nama_kabupaten: 'BELU',
    is_kota: 0,
    kode_provinsi: '53',
  },
  {
    kode_kabupaten: '5309',
    nama_kabupaten: 'NGADA',
    is_kota: 0,
    kode_provinsi: '53',
  },
  {
    kode_kabupaten: '5314',
    nama_kabupaten: 'ROTE NDAO',
    is_kota: 0,
    kode_provinsi: '53',
  },
  {
    kode_kabupaten: '5319',
    nama_kabupaten: 'MANGGARAI TIMUR',
    is_kota: 0,
    kode_provinsi: '53',
  },
  {
    kode_kabupaten: '6102',
    nama_kabupaten: 'MEMPAWAH',
    is_kota: 0,
    kode_provinsi: '61',
  },
  {
    kode_kabupaten: '6107',
    nama_kabupaten: 'BENGKAYANG',
    is_kota: 0,
    kode_provinsi: '61',
  },
  {
    kode_kabupaten: '6112',
    nama_kabupaten: 'KUBU RAYA',
    is_kota: 0,
    kode_provinsi: '61',
  },
  {
    kode_kabupaten: '6203',
    nama_kabupaten: 'KAPUAS',
    is_kota: 0,
    kode_provinsi: '62',
  },
  {
    kode_kabupaten: '6208',
    nama_kabupaten: 'SUKAMARA',
    is_kota: 0,
    kode_provinsi: '62',
  },
  {
    kode_kabupaten: '6213',
    nama_kabupaten: 'BARITO TIMUR',
    is_kota: 0,
    kode_provinsi: '62',
  },
  {
    kode_kabupaten: '6304',
    nama_kabupaten: 'BARITO KUALA',
    is_kota: 0,
    kode_provinsi: '63',
  },
  {
    kode_kabupaten: '6309',
    nama_kabupaten: 'TABALONG',
    is_kota: 0,
    kode_provinsi: '63',
  },
  {
    kode_kabupaten: '6401',
    nama_kabupaten: 'PASER',
    is_kota: 0,
    kode_provinsi: '64',
  },
  {
    kode_kabupaten: '6409',
    nama_kabupaten: 'PENAJAM PASER UTARA',
    is_kota: 0,
    kode_provinsi: '64',
  },
  {
    kode_kabupaten: '6501',
    nama_kabupaten: 'BULUNGAN',
    is_kota: 0,
    kode_provinsi: '65',
  },
  {
    kode_kabupaten: '7101',
    nama_kabupaten: 'BOLAANG MONGONDOW',
    is_kota: 0,
    kode_provinsi: '71',
  },
  {
    kode_kabupaten: '7106',
    nama_kabupaten: 'MINAHASA UTARA',
    is_kota: 0,
    kode_provinsi: '71',
  },
  {
    kode_kabupaten: '7111',
    nama_kabupaten: 'BOLAANG MONGONDOW SELATAN',
    is_kota: 0,
    kode_provinsi: '71',
  },
  {
    kode_kabupaten: '7201',
    nama_kabupaten: 'BANGGAI',
    is_kota: 0,
    kode_provinsi: '72',
  },
  {
    kode_kabupaten: '7206',
    nama_kabupaten: 'MOROWALI',
    is_kota: 0,
    kode_provinsi: '72',
  },
  {
    kode_kabupaten: '7211',
    nama_kabupaten: 'BANGGAI LAUT',
    is_kota: 0,
    kode_provinsi: '72',
  },
  {
    kode_kabupaten: '7303',
    nama_kabupaten: 'BANTAENG',
    is_kota: 0,
    kode_provinsi: '73',
  },
  {
    kode_kabupaten: '7308',
    nama_kabupaten: 'BONE',
    is_kota: 0,
    kode_provinsi: '73',
  },
  {
    kode_kabupaten: '7313',
    nama_kabupaten: 'WAJO',
    is_kota: 0,
    kode_provinsi: '73',
  },
  {
    kode_kabupaten: '7318',
    nama_kabupaten: 'TANA TORAJA',
    is_kota: 0,
    kode_provinsi: '73',
  },
  {
    kode_kabupaten: '7372',
    nama_kabupaten: 'KOTA PARE PARE',
    is_kota: 1,
    kode_provinsi: '73',
  },
  {
    kode_kabupaten: '7404',
    nama_kabupaten: 'BUTON',
    is_kota: 0,
    kode_provinsi: '74',
  },
  {
    kode_kabupaten: '7409',
    nama_kabupaten: 'KONAWE UTARA',
    is_kota: 0,
    kode_provinsi: '74',
  },
  {
    kode_kabupaten: '7414',
    nama_kabupaten: 'BUTON TENGAH',
    is_kota: 0,
    kode_provinsi: '74',
  },
  {
    kode_kabupaten: '7502',
    nama_kabupaten: 'BOALEMO',
    is_kota: 0,
    kode_provinsi: '75',
  },
  {
    kode_kabupaten: '7601',
    nama_kabupaten: 'MAMUJU UTARA',
    is_kota: 0,
    kode_provinsi: '76',
  },
  {
    kode_kabupaten: '7606',
    nama_kabupaten: 'MAMUJU TENGAH',
    is_kota: 0,
    kode_provinsi: '76',
  },
  {
    kode_kabupaten: '8105',
    nama_kabupaten: 'SERAM BAGIAN TIMUR',
    is_kota: 0,
    kode_provinsi: '81',
  },
  {
    kode_kabupaten: '8171',
    nama_kabupaten: 'KOTA AMBON',
    is_kota: 1,
    kode_provinsi: '81',
  },
  {
    kode_kabupaten: '8204',
    nama_kabupaten: 'HALMAHERA SELATAN',
    is_kota: 0,
    kode_provinsi: '82',
  },
  {
    kode_kabupaten: '8271',
    nama_kabupaten: 'KOTA TERNATE',
    is_kota: 1,
    kode_provinsi: '82',
  },
  {
    kode_kabupaten: '9104',
    nama_kabupaten: 'NABIRE',
    is_kota: 0,
    kode_provinsi: '91',
  },
  {
    kode_kabupaten: '9109',
    nama_kabupaten: 'MIMIKA',
    is_kota: 0,
    kode_provinsi: '91',
  },
  {
    kode_kabupaten: '9114',
    nama_kabupaten: 'TOLIKARA',
    is_kota: 0,
    kode_provinsi: '91',
  },
  {
    kode_kabupaten: '9119',
    nama_kabupaten: 'SUPIORI',
    is_kota: 0,
    kode_provinsi: '91',
  },
  {
    kode_kabupaten: '9124',
    nama_kabupaten: 'NDUGA',
    is_kota: 0,
    kode_provinsi: '91',
  },
  {
    kode_kabupaten: '9171',
    nama_kabupaten: 'KOTA JAYAPURA',
    is_kota: 1,
    kode_provinsi: '91',
  },
  {
    kode_kabupaten: '9205',
    nama_kabupaten: 'RAJA AMPAT',
    is_kota: 0,
    kode_provinsi: '92',
  },
  {
    kode_kabupaten: '9210',
    nama_kabupaten: 'MAYBRAT',
    is_kota: 0,
    kode_provinsi: '92',
  },
];
